### PR TITLE
switched to new pybind11.get_include() API; minor PEP8 fixes

### PR DESCRIPTION
**Pull request by wjakob**
This PR implements the changes discussed in #8 now that a new version of pybind11 is available.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
What does the `user=True` stand for?

**Comment by benmaier** [comment]
Doing so passes back the path of the `include` directory in case one installed `pybind11` using the `--user` flag.

**Comment by SylvainCorlay** [comment]
Thanks@benmaier. This is what I thought.

I would recommend not using user installs in general, and especially in the case of modules that can be dependencies to others.

The issue is that if you have multiple python installs (e.g. two different anaconda distributions installs, Anaconda1 and Anaconda2), the user directory, which is under `~/.local` on linux has priority over any other one in your python path.

Hence, if you install a version of a `foobar` package with  `--user` in `Anaconda1`, it will be picked up by `Anaconda2` when you try to import it even if `Anaconda2` already has this module installed under its sys-prefix, with a different version. Having a single module installed as a user can lead to crazy behaviors if this module is a common dependency for other things... Now when it comes to something like pybind, which may be installed in both anaconda1 and anaconda2, you can see the consequences of such border effects...

IMO, for 99% of the use cases, an ordinary sys prefix install is preferable, and users performing user installs deserve whatever happens to them :)

I would be more comfortable removing the line with `user=True` in this example.

**Comment by wjakob** [comment]
Hi Sylvain,

note that both paths are specified, and the system path has precedence. So I don't think there is an issue here.

-Wenzel

**Comment by SylvainCorlay** [comment]
@wjakob I can't find a reference for precedence in `include_dirs`.

**Comment by wjakob** [comment]
It might not be explicitly documented, but preserving ordering in include file paths is an important aspect in any kind of C/C++ build system. I just tried this on my machine and found that the actual order matches that provided in the ``include_dirs`` parameter, i.e. I get

```
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/Users/wjakob/Library/Python/2.7/include/python2.7
```

**Comment by wjakob** [comment]
Can we move to merge this in the absence of a compelling alternative? :)

**Comment by wjakob** [comment]
(In any case, if there is a way of doing all of this without pip, the piece of code that needs to change is in pybind11 and not here)

**Pull request merged**
